import unittest

class TC(unittest.TestCase):
    @unittest.expectedFailure
    def test(self):
        pass
